[package]
name = "microslop"
version = "0.3.3"
authors = ["Anatnaso <antondev@kuthy.com>"]
edition = "2024"
description = "Turn your text into beautifully chaotic, glitchy, Wandoze-level slop."
license = "MIT"
repository = "https://github.com/Anothernaso/microslop"
homepage = "https://github.com/Anothernaso/microslop"
keywords = ["glitch", "slop", "text", "unicode"]
categories = ["text-processing"]

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
randix = "0.2.0"
